--[[pod_format="raw",created="2026-08-01 07:55:13",modified="2026-08-11 17:31:55",revision=28]]
----------------------------------------------------------------------
-- CONFIG
----------------------------------------------------------------------
-- Global constants: screen/playfield dimensions, frame/HUD geometry,
-- sprite indices, brick/ball/paddle sizes, and color values.
-- All values are read-only at runtime.
----------------------------------------------------------------------

VERSION = "v0.2.0-beta"

SCREEN_WIDTH  = 480
SCREEN_HEIGHT = 270

TOP_MARGIN  = 8
LEFT_MARGIN = 25
FRAME_SIZE  = 8

GAME_WIDTH  = 222
GAME_HEIGHT = 254

GAME_BOTTOM = SCREEN_HEIGHT - 1

FRAME_WIDTH  = GAME_WIDTH + FRAME_SIZE * 2
FRAME_HEIGHT = GAME_HEIGHT + FRAME_SIZE
FRAME_TILE_SIZE = 16

FRAME_X = LEFT_MARGIN

GAME_X = FRAME_X + FRAME_SIZE
GAME_Y = SCREEN_HEIGHT - GAME_HEIGHT

GAME_RIGHT = GAME_X + GAME_WIDTH - 1

FRAME_Y = GAME_Y - FRAME_SIZE

HUD_X = FRAME_X + FRAME_WIDTH
HUD_Y = 0
HUD_WIDTH = SCREEN_WIDTH - HUD_X
HUD_HEIGHT = SCREEN_HEIGHT

SPR_FRAME_CORNER   = 24
SPR_FRAME_DECOR_A  = 32
SPR_FRAME_DECOR_B  = 40
SPR_FRAME_CLAMP_L  = 25
SPR_FRAME_CLAMP_R  = 26

PADDLE_WIDTH  = 32
PADDLE_WIDTH_LARGE = 48
PADDLE_HEIGHT = 8
PADDLE_BOTTOM_MARGIN = 18
PADDLE_SPRITE = 8
PADDLE_SPRITE_SHADOW = 12
PADDLE_SPRITE_LASER = 16
PADDLE_ANIMATION = {8, 9, 10, 11, 10, 9}
PADDLE_ANIMATION_LASER = {16, 17, 18, 19, 18, 17}
PADDLE_ANIMATION_SPEED = 3
	
BRICK_WIDTH  = 16
BRICK_HEIGHT = 8
BRICK_SPACING_X = 1
BRICK_SPACING_Y = 1
BRICK_FLASH = 18

BRICKS_X = FRAME_X + FRAME_SIZE
BRICKS_Y = FRAME_Y + FRAME_SIZE + (BRICK_HEIGHT*3) 

BALL_SPEED_NORMAL = 2.5
BALL_SPEED_SLOW   = 1.5
BALL_SPRITE = 1
BALL_SPRITE_MEGA = 2
BALL_DIAG = 1 / sqrt(2)

GOLD_HITS_MAX = 10
GOLD_DEFLECT = 0.2
BALL_STUCK_TIMEOUT = 480
BALL_NUDGE_STRENGTH = 0.35

SPR_PILL_SHADOW = 48

SHADOW_COLOR = 40

SHADOW_COL = 32
SHADOW_STENCIL_MASK = 0x7f7f7f7f
SHADOW_DEFAULT_MASK = 0x3f3f3f
